// Simple PDF export utility
// In a production environment, you'd use a library like jsPDF or react-pdf

export const exportToPDF = (results, productDescription) => {
  // Create a formatted text content for PDF
  const formatDate = () => {
    return new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const content = `
HTS CLASSIFICATION REPORT
Generated: ${formatDate()}

PRODUCT DESCRIPTION:
${productDescription}

CLASSIFICATION RESULTS:
${results.map((result, index) => `
${index + 1}. HTS CODE: ${result.hts_code}
   Description: ${result.description}
   Effective Duty: ${result.effective_duty}
   Confidence Score: ${result.confidence_score}%
   Data Source: ${result.duty_source}
   ${result.special_duty ? `Special Duty: ${result.special_duty}` : ''}
   ${result.unit ? `Unit of Quantity: ${result.unit}` : ''}
`).join('\n')}

IMPORTANT DISCLAIMER:
This classification is provided for reference purposes only. Final HTS 
classification should be verified with a licensed customs broker or through 
official CBP ruling procedures. Duty rates and regulations are subject to change.

For official USITC HTS data, visit: https://hts.usitc.gov

Generated by HTS Oracle Classification Assistant
  `;

  // Create a blob and download
  const blob = new Blob([content], { type: 'text/plain' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `HTS_Classification_${productDescription.replace(/[^a-zA-Z0-9]/g, '_')}_${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};

// Enhanced PDF export with HTML formatting (for future implementation)
export const exportToHTMLReport = (results, productDescription) => {
  const formatDate = () => {
    return new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <title>HTS Classification Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        .header { border-bottom: 2px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; }
        .title { color: #1d4ed8; font-size: 24px; font-weight: bold; }
        .subtitle { color: #6b7280; font-size: 14px; margin-top: 5px; }
        .section { margin: 20px 0; }
        .section-title { color: #374151; font-size: 18px; font-weight: bold; margin-bottom: 10px; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
        .result-card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin: 15px 0; background: #f9fafb; }
        .hts-code { font-size: 20px; font-weight: bold; color: #1d4ed8; }
        .confidence { color: #059669; font-weight: bold; }
        .duty { color: #dc2626; font-weight: bold; }
        .disclaimer { background: #fef3c7; border: 1px solid #f59e0b; border-radius: 8px; padding: 15px; margin-top: 30px; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th, td { padding: 8px; text-align: left; border-bottom: 1px solid #e5e7eb; }
        th { background-color: #f3f4f6; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">HTS Classification Report</div>
        <div class="subtitle">Generated: ${formatDate()}</div>
    </div>

    <div class="section">
        <div class="section-title">Product Description</div>
        <p>${productDescription}</p>
    </div>

    <div class="section">
        <div class="section-title">Classification Results</div>
        ${results.map((result, index) => `
        <div class="result-card">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px;">
                <span class="hts-code">${result.hts_code}</span>
                <span class="confidence">${result.confidence_score}% Match</span>
            </div>
            
            <table>
                <tr><th>Description</th><td>${result.description}</td></tr>
                <tr><th>Effective Duty</th><td class="duty">${result.effective_duty}</td></tr>
                ${result.special_duty ? `<tr><th>Special Duty</th><td>${result.special_duty}</td></tr>` : ''}
                ${result.unit ? `<tr><th>Unit of Quantity</th><td>${result.unit}</td></tr>` : ''}
                <tr><th>Data Source</th><td>${result.duty_source}</td></tr>
                <tr><th>Match Type</th><td>${result.match_type}</td></tr>
            </table>
        </div>
        `).join('')}
    </div>

    <div class="disclaimer">
        <strong>Important Disclaimer:</strong> This classification is provided for reference purposes only. 
        Final HTS classification should be verified with a licensed customs broker or through official CBP 
        ruling procedures. Duty rates and regulations are subject to change.<br><br>
        For official USITC HTS data, visit: <a href="https://hts.usitc.gov">https://hts.usitc.gov</a><br><br>
        Generated by HTS Oracle Classification Assistant
    </div>
</body>
</html>
  `;

  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `HTS_Classification_Report_${productDescription.replace(/[^a-zA-Z0-9]/g, '_')}_${Date.now()}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};